-- MySQL Script generated by MySQL Workbench
-- 12/09/16 22:16:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema balounj_web_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `balounj_web_db` ;

-- -----------------------------------------------------
-- Schema balounj_web_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `balounj_web_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `balounj_web_db` ;

-- -----------------------------------------------------
-- Table `balounj_web_db`.`UCTY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balounj_web_db`.`UCTY` ;

CREATE TABLE IF NOT EXISTS `balounj_web_db`.`UCTY` (
  `login` VARCHAR(45) NOT NULL,
  `heslo` VARCHAR(300) NOT NULL,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `prava` VARCHAR(20) NULL DEFAULT 'autor',
  `blokovan` VARCHAR(5) NULL DEFAULT 'n',
  PRIMARY KEY (`login`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `balounj_web_db`.`PRISPEVKY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balounj_web_db`.`PRISPEVKY` ;

CREATE TABLE IF NOT EXISTS `balounj_web_db`.`PRISPEVKY` (
  `id_prispevku` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(200) NOT NULL,
  `autori` VARCHAR(300) NOT NULL,
  `abstract` VARCHAR(1000) NULL,
  `koncovka` VARCHAR(45) NULL,
  `nazev_pdf` VARCHAR(255) NULL,
  `pdf` LONGBLOB NULL,
  `stav` VARCHAR(45) NOT NULL DEFAULT 'v recenzním řízení',
  `hodnoceni` VARCHAR(45) NULL,
  `UCTY_login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_prispevku`),
  INDEX `fk_PRISPEVKY_UCTY1_idx` (`UCTY_login` ASC),
  CONSTRAINT `fk_PRISPEVKY_UCTY1`
    FOREIGN KEY (`UCTY_login`)
    REFERENCES `balounj_web_db`.`UCTY` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `balounj_web_db`.`RECENZE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balounj_web_db`.`RECENZE` ;

CREATE TABLE IF NOT EXISTS `balounj_web_db`.`RECENZE` (
  `id_recenze` INT NOT NULL AUTO_INCREMENT,
  `originalita` INT NULL,
  `tema` INT NULL,
  `kvalita` INT NULL,
  `prijmout` INT NULL,
  `info` VARCHAR(500) NULL,
  `PRISPEVKY_id_prispevku` INT NOT NULL,
  `UCTY_login` VARCHAR(45) NOT NULL,
  `stav` VARCHAR(45) NULL DEFAULT 'zadáno',
  PRIMARY KEY (`id_recenze`),
  INDEX `fk_RECENZE_PRISPEVKY1_idx` (`PRISPEVKY_id_prispevku` ASC),
  INDEX `fk_RECENZE_UCTY1_idx` (`UCTY_login` ASC),
  CONSTRAINT `fk_RECENZE_PRISPEVKY1`
    FOREIGN KEY (`PRISPEVKY_id_prispevku`)
    REFERENCES `balounj_web_db`.`PRISPEVKY` (`id_prispevku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECENZE_UCTY1`
    FOREIGN KEY (`UCTY_login`)
    REFERENCES `balounj_web_db`.`UCTY` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
